version: "3.8"

services:
  web:
    image: aungkhantmin21/weather-dashboard-client:latest
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./web:/app
  redis:
    image: redis:8.4.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass DRKURFacItkpoFNuS7OMPg==
    restart: unless-stopped
  server:
    image: aungkhantmin21/weather-dashboard-server:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=DRKURFacItkpoFNuS7OMPg==
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./server:/app
