apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: aungkhantmin21/weather-dashboard-client:v1.0.1
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "/api"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: weather-config
              key: NODE_ENV

---

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
